# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# .goreleaser.yaml

project_name: ufo

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ufo
    env:
      - CGO_ENABLED=0
      - GONOSUMDB=*
      - GOTOOLCHAIN=go1.27.1
      - GOPROXY=https://proxy.golang.org,https://goproxy.cn,https://goproxy.io,direct
    main: ./cmd/ufo
    binary: ufo
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X "github.com/btwiuse/version.MajorString=0"
      - -s -w -X "github.com/btwiuse/version.MinorString=6"
      - -s -w -X "github.com/btwiuse/version.GitCommitString={{.Commit}}"
      - -s -w -X "github.com/btwiuse/version.GitTreeStateString=clean"
      - -s -w -X "github.com/btwiuse/version.GitVersionString={{.Version}}"
      - -s -w -X "github.com/btwiuse/version.BuildDateString={{.Date}}"
    targets:
      - linux_amd64_v1
      - linux_arm64_v8.0
      - linux_386_sse2
      - linux_arm_6
      - linux_arm_7
      - linux_riscv64_rva22u64
      - darwin_amd64_v1
      - darwin_arm64_v8.0
      - windows_amd64_v1
      - windows_arm64_v8.0
      - windows_386_sse2
      - android_arm64_v8.0

archives:
  - id: archive
    ids:
      - ufo
    files:
      - LICENSE
    name_template: >-
      {{ .ProjectName }}-{{- .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"
